"""Sync DB → .py seed files for all seed-tracked interactions.

Usage:
    ./dev python3 -m servers.tools.sync_prompts            # sync all
    ./dev python3 -m servers.tools.sync_prompts --check    # non-zero exit if any file is out of sync

Architecture reminder:
    - The DB's interactions table is AUTHORITATIVE at runtime.
    - The sibling .py files (encoding_prompt.py, community_enrichment_prompt.py,
      consolidation_enrichment_prompt.py, healer_prompt.py) are SEED-ONLY. They
      bootstrap fresh brains that have no entry for the interaction yet.
    - This tool keeps .py files mirrored to the DB's LATEST version so a fresh
      clone of the repo reflects the mature prompts — not a stale v1 baseline.
    - Run this before committing any prompt change so git history captures it.
"""
import argparse
import os
import sqlite3
import sys
from datetime import datetime, timezone


# interaction_name → (file path relative to repo root, constant name)
SEED_PROMPTS = [
    ('s1e',
     'servers/scales/s1/encoding_prompt.py',
     'SYSTEM_PROMPT'),
    ('s2_community_enrichment',
     'servers/scales/s2/community_enrichment_prompt.py',
     'SYSTEM_PROMPT'),
    ('s2_consolidation_enrichment',
     'servers/scales/s2/consolidation_enrichment_prompt.py',
     'SYSTEM_PROMPT'),
    ('s2_healer',
     'servers/scales/s2/healer_prompt.py',
     'SYSTEM_PROMPT'),
    # S1 Scout prompts. Temporal is algo-first; its template is a Haiku
    # fallback reserved for future use but kept in sync so the DB entry
    # stays coherent if the fallback path is wired later.
    ('s1_scout_quote',
     'servers/scales/s1/scouts/prompts/quote_prompt.py',
     'SYSTEM_PROMPT'),
    ('s1_scout_temporal',
     'servers/scales/s1/scouts/prompts/temporal_prompt.py',
     'SYSTEM_PROMPT'),
    ('s1_scout_facts',
     'servers/scales/s1/scouts/prompts/facts_prompt.py',
     'SYSTEM_PROMPT'),
]


def _repo_root():
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.dirname(os.path.dirname(here))


def _fetch_active(conn, name):
    """Active template + version + parameters for an interaction, or None.

    The seed file mirrors the PRODUCTION-RUNNING version (active), NOT the
    highest registered version. Dormant candidates (registered but not yet
    activated — e.g. during a 3-way eval gate) must NOT leak into the seed
    file, or fresh brains would skip the eval gate by booting with the
    untested candidate as their v1 active.

    Falls back to highest version only if no row has active=1 (defensive —
    every registered interaction should have exactly one active row).
    """
    # interaction_active is a separate pointer table — one row per name
    # carrying the version that the runtime reads. JOIN to interactions for
    # the actual template content.
    row = conn.execute(
        'SELECT i.template, i.version, i.parameters, i.created_by, i.created_at '
        'FROM interactions i '
        'JOIN interaction_active ia ON ia.name = i.name AND ia.version = i.version '
        'WHERE i.name = ? LIMIT 1',
        (name,)).fetchone()
    if not row:
        # Defensive fallback — should never happen on a healthy table.
        row = conn.execute(
            'SELECT template, version, parameters, created_by, created_at '
            'FROM interactions WHERE name = ? ORDER BY version DESC LIMIT 1',
            (name,)).fetchone()
    if not row:
        return None
    return {'template': row[0], 'version': row[1],
            'parameters': row[2], 'created_by': row[3],
            'created_at': row[4]}


def _render_py(name, constant, interaction):
    """Build the exact text of the .py seed file.

    Kept minimal: a docstring explaining the seed role, the SYSTEM_PROMPT
    constant as a triple-quoted raw-ish string, and no imports. Consumers
    use `from X import SYSTEM_PROMPT`.
    """
    # The template may contain literal backslash sequences (e.g. "\n" as two
    # chars inside a JSON example in the prompt). Inside a """...""" literal,
    # Python would interpret those — so we escape every backslash first, then
    # any triple-quotes for the outer delimiter.
    body = (interaction['template']
            .replace('\\', '\\\\')
            .replace('"""', '\\"\\"\\"'))
    return (
        '"""Seed for interaction `%s` — DB is authoritative at runtime.\n'
        '\n'
        'This file ONLY bootstraps fresh brains that have no entry for %s yet.\n'
        'The runtime path (brain.get_interaction_prompt) always reads the DB.\n'
        'Do NOT edit this file to change prompt behavior — use register_interaction\n'
        '+ set_interaction_active, then run `./dev python3 -m servers.tools.sync_prompts`\n'
        'to mirror the ACTIVE version into this file.\n'
        '\n'
        'Sync mirrors the production-ACTIVE version, not the highest registered.\n'
        'Dormant candidates (registered but not yet activated — e.g. during a\n'
        '3-way eval gate) are deliberately excluded from the seed so fresh brains\n'
        'cannot bypass the eval gate by booting with an untested candidate.\n'
        '\n'
        'Last sync: DB v%d (%s, by %s).\n'
        '"""\n'
        '\n'
        'SYSTEM_PROMPT = """%s"""\n'
        % (name, name, interaction['version'],
           interaction['created_at'][:19] if interaction.get('created_at') else '?',
           interaction.get('created_by') or '?',
           body)
    )


def _read_current_constant(path, constant):
    """Best-effort: extract `SYSTEM_PROMPT = \"\"\"…\"\"\"` from an existing file.

    Returns the string value, or None if the file is missing or the constant
    isn't in the expected shape. Used only to compute 'changed' for reports.
    """
    if not os.path.exists(path):
        return None
    try:
        ns = {}
        with open(path) as f:
            exec(compile(f.read(), path, 'exec'), ns)
        return ns.get(constant)
    except Exception:
        return None


def sync(conn, check_only=False, log=print):
    """Sync all seed prompts DB → .py. Returns list of (name, status) tuples.

    status ∈ {'synced', 'would-change', 'missing-in-db', 'no-change'}.
    check_only=True: print diff-summary only, don't write files.
    """
    root = _repo_root()
    results = []
    for name, rel_path, constant in SEED_PROMPTS:
        inter = _fetch_active(conn, name)
        if inter is None:
            results.append((name, 'missing-in-db'))
            log('  %-34s  missing in DB — seed cannot be synced' % name)
            continue
        path = os.path.join(root, rel_path)
        current = _read_current_constant(path, constant)
        fresh = inter['template']
        if current == fresh:
            results.append((name, 'no-change'))
            log('  %-34s  v%d  already in sync' % (name, inter['version']))
            continue
        if check_only:
            results.append((name, 'would-change'))
            log('  %-34s  v%d  OUT OF SYNC (%s chars -> %s chars)' % (
                name, inter['version'],
                '?' if current is None else len(current),
                len(fresh)))
            continue
        text = _render_py(name, constant, inter)
        with open(path, 'w') as f:
            f.write(text)
        results.append((name, 'synced'))
        log('  %-34s  v%d  wrote %s (%d chars)' % (
            name, inter['version'], rel_path, len(fresh)))
    return results


def main():
    parser = argparse.ArgumentParser(description='Sync DB interactions → seed .py files')
    parser.add_argument('--check', action='store_true',
                        help="Report out-of-sync files and exit non-zero; don't write.")
    parser.add_argument('--db', default=None,
                        help='Path to brain_logs.db (interactions table lives there). '
                             'Defaults to $BRAIN_DB_DIR/brain_logs.db.')
    args = parser.parse_args()

    db_path = args.db or os.path.join(
        os.environ.get('BRAIN_DB_DIR') or os.path.expanduser('~/AgentsContext/brain'),
        'brain_logs.db')
    if not os.path.exists(db_path):
        print('sync_prompts: brain_logs.db not found at %s' % db_path, file=sys.stderr)
        return 2

    conn = sqlite3.connect(db_path)
    results = sync(conn, check_only=args.check)
    conn.close()

    if args.check:
        drift = [r for r in results if r[1] == 'would-change']
        if drift:
            print('\n%d seed file(s) out of sync. Run: ./dev python3 -m servers.tools.sync_prompts'
                  % len(drift), file=sys.stderr)
            return 1
        print('\nAll seed files in sync with DB.')
        return 0
    return 0


if __name__ == '__main__':
    sys.exit(main())
