"""Sync DB → .py seed files for all seed-tracked interactions.

Usage:
    ./dev python3 -m servers.tools.sync_prompts            # sync all
    ./dev python3 -m servers.tools.sync_prompts --check    # non-zero exit if any file is out of sync

Architecture reminder:
    - The DB's interactions table is AUTHORITATIVE at runtime.
    - The sibling .py files (encoding_prompt.py, community_enrichment_prompt.py,
      consolidation_enrichment_prompt.py, healer_prompt.py) are SEED-ONLY. They
      bootstrap fresh brains that have no entry for the interaction yet.
    - This tool keeps .py files mirrored to the DB's LATEST version so a fresh
      clone of the repo reflects the mature prompts — not a stale v1 baseline.
    - Run this before committing any prompt change so git history captures it.
"""
import argparse
import json
import os
import re
import sqlite3
import sys
from datetime import datetime, timezone


# interaction_name → (file path relative to repo root, constant name)
SEED_PROMPTS = [
    ('s1e',
     'servers/scales/s1/encoding_prompt.py',
     'SYSTEM_PROMPT'),
    ('s2_community_enrichment',
     'servers/scales/s2/community_enrichment_prompt.py',
     'SYSTEM_PROMPT'),
    ('s2_consolidation_enrichment',
     'servers/scales/s2/consolidation_enrichment_prompt.py',
     'SYSTEM_PROMPT'),
    ('s2_healer',
     'servers/scales/s2/healer_prompt.py',
     'SYSTEM_PROMPT'),
    ('s2_aspects',
     'servers/scales/s2/aspect_prompt.py',
     'SYSTEM_PROMPT'),
    # S1 Scout prompts. Temporal is algo-first; its template is a Haiku
    # fallback reserved for future use but kept in sync so the DB entry
    # stays coherent if the fallback path is wired later.
    ('s1_scout_quote',
     'servers/scales/s1/scouts/prompts/quote_prompt.py',
     'SYSTEM_PROMPT'),
    ('s1_scout_temporal',
     'servers/scales/s1/scouts/prompts/temporal_prompt.py',
     'SYSTEM_PROMPT'),
    ('s1_scout_facts',
     'servers/scales/s1/scouts/prompts/facts_prompt.py',
     'SYSTEM_PROMPT'),
    ('surface',
     'servers/scales/s1/surface_prompt.py',
     'SYSTEM_PROMPT'),
    # Recall-lane query expansion. Env-gated off by default, so it is NOT in
    # shipped_prompts() — but its seed must still mirror ACTIVE, or a dormant
    # candidate could leak into fresh brains through the seed file.
    ('recall_query_expansion',
     'servers/recall_expansion_prompt.py',
     'SYSTEM_PROMPT'),
]


def _repo_root():
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.dirname(os.path.dirname(here))


def _fetch_active(conn, name):
    """DEPLOYED override (template + version + parameters), or None.

    The seed file mirrors the DEPLOYED version (the interaction_active
    pointer), NEVER the highest registered one. Dormant candidates
    (registered but not yet activated — e.g. during a 3-way eval gate) must
    NOT leak into the seed file: the seed .py IS the code default
    (interaction_defaults imports it), so a leak would deploy an untested
    prompt fleet-wide. "No pointer" is the normal state under the override
    model — it means no override is deployed and the seed .py is already
    authoritative, so None here means "nothing to mirror", never "fall back
    to MAX(version)".
    """
    # interaction_active is a separate pointer table — one row per name
    # carrying the version that the runtime reads. JOIN to interactions for
    # the actual template content.
    row = conn.execute(
        'SELECT i.template, i.version, i.parameters, i.created_by, i.created_at '
        'FROM interactions i '
        'JOIN interaction_active ia ON ia.name = i.name AND ia.version = i.version '
        'WHERE i.name = ? LIMIT 1',
        (name,)).fetchone()
    if not row:
        return None
    return {'template': row[0], 'version': row[1],
            'parameters': row[2], 'created_by': row[3],
            'created_at': row[4]}


def _render_py(name, constant, interaction):
    """Build the exact text of the .py seed file.

    Kept minimal: a docstring explaining the seed role, the SYSTEM_PROMPT
    constant as a triple-quoted raw-ish string, and no imports. Consumers
    use `from X import SYSTEM_PROMPT`.
    """
    # The template may contain literal backslash sequences (e.g. "\n" as two
    # chars inside a JSON example in the prompt). Inside a """...""" literal,
    # Python would interpret those — so we escape every backslash first, then
    # any triple-quotes for the outer delimiter.
    body = (interaction['template']
            .replace('\\', '\\\\')
            .replace('"""', '\\"\\"\\"'))
    return (
        '"""Seed for interaction `%s` — DB is authoritative at runtime.\n'
        '\n'
        'This file ONLY bootstraps fresh brains that have no entry for %s yet.\n'
        'The runtime path (brain.get_interaction_prompt) always reads the DB.\n'
        'Do NOT edit this file to change prompt behavior — use register_interaction\n'
        '+ set_interaction_active, then run `./dev python3 -m servers.tools.sync_prompts`\n'
        'to mirror the ACTIVE version into this file.\n'
        '\n'
        'Sync mirrors the production-ACTIVE version, not the highest registered.\n'
        'Dormant candidates (registered but not yet activated — e.g. during a\n'
        '3-way eval gate) are deliberately excluded from the seed so fresh brains\n'
        'cannot bypass the eval gate by booting with an untested candidate.\n'
        '\n'
        'Last sync: DB v%d (%s, by %s).\n'
        '"""\n'
        '\n'
        'SYSTEM_PROMPT = """%s"""\n'
        % (name, name, interaction['version'],
           interaction['created_at'][:19] if interaction.get('created_at') else '?',
           interaction.get('created_by') or '?',
           body)
    )


def _read_current_constant(path, constant):
    """Best-effort: extract `SYSTEM_PROMPT = \"\"\"…\"\"\"` from an existing file.

    Returns the string value, or None if the file is missing or the constant
    isn't in the expected shape. Used only to compute 'changed' for reports.
    """
    if not os.path.exists(path):
        return None
    try:
        ns = {}
        with open(path) as f:
            exec(compile(f.read(), path, 'exec'), ns)
        return ns.get(constant)
    except Exception:
        return None


# The provenance line _render_py writes. Parsed back out so a stale version can
# be detected and repaired WITHOUT regenerating the file: everything else in a
# seed docstring may be hand-written (a note that this prompt is a dormant
# fallback, a pointer to where the real code lives), and whole-file
# regeneration silently eats it.
_LAST_SYNC_RE = re.compile(r'^Last sync: DB v(\d+) .*$', re.MULTILINE)


def _read_header_version(path):
    """Version recorded in the file's `Last sync:` line, or None if absent.

    None means the header carries no provenance line at all (hand-written seed,
    or an older template) — treated as drift so it gets one.
    """
    try:
        with open(path, encoding='utf-8') as f:
            m = _LAST_SYNC_RE.search(f.read())
    except (OSError, UnicodeDecodeError):
        return None
    return int(m.group(1)) if m else None


def _patch_header_version(path, interaction):
    """Correct the file's `Last sync:` provenance in place. True if patched.

    The surgical repair for the header-stale case: the body already matches the
    active version, so the file needs its provenance corrected, not rebuilt.
    Preserves every other line, including hand-written documentation — a seed
    docstring may carry notes a regenerate cannot reproduce (that a prompt is a
    dormant fallback, where the real code lives).

    Two shapes handled: an existing `Last sync:` line is replaced; a docstring
    with no provenance line at all gets one appended as its last line. Returns
    False only when there's no module docstring to patch, leaving the caller to
    fall back to a full regenerate.
    """
    try:
        with open(path, encoding='utf-8') as f:
            text = f.read()
    except (OSError, UnicodeDecodeError):
        return False
    fresh_line = 'Last sync: DB v%d (%s, by %s).' % (
        interaction['version'],
        interaction['created_at'][:19] if interaction.get('created_at') else '?',
        interaction.get('created_by') or '?')
    patched, n = _LAST_SYNC_RE.subn(lambda _m: fresh_line, text, count=1)
    if not n:
        # No provenance line — insert one at the end of the module docstring.
        if not text.startswith('"""'):
            return False
        close = text.find('"""', 3)
        if close == -1:
            return False
        head = text[:close].rstrip('\n')
        patched = '%s\n\n%s\n%s' % (head, fresh_line, text[close:])
    with open(path, 'w', encoding='utf-8') as f:
        f.write(patched)
    return True


def check_configs(conn, log=print):
    """Report seed config dicts that have drifted from the active config.

    Reported, never rewritten. The template halves are machine-generated files,
    but the config dicts live inline in `interaction_seed.py` with comments
    explaining each value, and a regenerate would eat them.

    This exists because the two halves had different maintenance models and the
    config half rotted silently: `s2_community_enrichment` carried a DATED model
    id long after production moved off it, and the shipped-prompt reconcile
    publishes config alongside the template. A fingerprint test cannot catch this
    — it detects changes TO the dict, never the dict drifting FROM the DB.

    Returns a list of (name, 'config-drift'|'config-ok') tuples.
    """
    from ..interaction_seed import shipped_prompts

    results = []
    for name, (_template, shipped_cfg) in sorted(shipped_prompts().items()):
        inter = _fetch_active(conn, name)
        if inter is None:
            continue  # no override deployed — nothing to compare against
        try:
            live_cfg = json.loads(inter['parameters']) if inter['parameters'] else {}
        except (json.JSONDecodeError, TypeError):
            live_cfg = {}
        if live_cfg == shipped_cfg:
            results.append((name, 'config-ok'))
            continue
        shipped_only = sorted(set(shipped_cfg) - set(live_cfg))
        live_only = sorted(set(live_cfg) - set(shipped_cfg))
        changed = sorted(k for k in set(shipped_cfg) & set(live_cfg)
                         if shipped_cfg[k] != live_cfg[k])
        results.append((name, 'config-drift'))
        log('  %-34s  v%d  CONFIG DRIFT' % (name, inter['version']))
        for label, keys in (('only in seed', shipped_only),
                            ('only in DB', live_only),
                            ('differing', changed)):
            if keys:
                log('      %-13s %s' % (label + ':', ', '.join(keys)))
    return results


def sync(conn, check_only=False, log=print):
    """Sync all seed prompts DB → .py. Returns list of (name, status) tuples.

    status ∈ {'synced', 'would-change', 'no-override', 'no-change'}.
    check_only=True: print diff-summary only, don't write files.
    """
    root = _repo_root()
    results = []
    for name, rel_path, constant in SEED_PROMPTS:
        inter = _fetch_active(conn, name)
        if inter is None:
            # No override deployed — the seed .py is already the authority
            # (it IS the code default). Nothing to mirror, healthy state.
            results.append((name, 'no-override'))
            log('  %-34s  no override deployed — seed file is authoritative'
                % name)
            continue
        path = os.path.join(root, rel_path)
        fresh = inter['template']
        # TWO independent comparisons, because they have different repairs:
        #   body   — the prompt constant vs the active template. Wrong body =
        #            the seed would boot a fresh brain on the wrong prompt.
        #            Repair is a full regenerate.
        #   header — the version in the `Last sync:` line vs the active version.
        #            A hand-edited-then-registered seed has a correct body and a
        #            lying header, and constant-only comparison called that
        #            "in sync". Repair is a one-line patch, NOT a regenerate:
        #            the rest of the docstring may be hand-written and a
        #            regenerate would silently delete it.
        current = _read_current_constant(path, constant)
        body_ok = (current == fresh)
        header_ok = (_read_header_version(path) == inter['version'])
        if body_ok and header_ok:
            results.append((name, 'no-change'))
            log('  %-34s  v%d  already in sync' % (name, inter['version']))
            continue
        if check_only:
            drift = 'header' if body_ok else 'body'
            results.append((name, 'would-change'))
            log('  %-34s  v%d  OUT OF SYNC (%s: %s chars -> %s chars)' % (
                name, inter['version'], drift,
                '?' if current is None else len(current),
                len(fresh)))
            continue
        if body_ok and _patch_header_version(path, inter):
            results.append((name, 'synced'))
            log('  %-34s  v%d  patched header in %s' % (
                name, inter['version'], rel_path))
            continue
        with open(path, 'w') as f:
            f.write(_render_py(name, constant, inter))
        results.append((name, 'synced'))
        log('  %-34s  v%d  wrote %s (%d chars)' % (
            name, inter['version'], rel_path, len(fresh)))
    return results


def main():
    parser = argparse.ArgumentParser(description='Sync DB interactions → seed .py files')
    parser.add_argument('--check', action='store_true',
                        help="Report out-of-sync files and exit non-zero; don't write.")
    parser.add_argument('--db', default=None,
                        help='Path to brain_logs.db (interactions table lives there). '
                             'Defaults to brain_logs.db in the resolved '
                             'brain dir (daemon_config.resolve_db_dir).')
    args = parser.parse_args()

    from servers.daemon_config import resolve_db_dir
    db_path = args.db or os.path.join(resolve_db_dir(), 'brain_logs.db')
    if not os.path.exists(db_path):
        print('sync_prompts: brain_logs.db not found at %s' % db_path, file=sys.stderr)
        return 2

    conn = sqlite3.connect(db_path)
    results = sync(conn, check_only=args.check)
    # Config drift is reported on both paths: the seed configs ride to the fleet
    # next to the templates, so a stale one is a shipping defect, not a nit.
    config_results = check_configs(conn)
    conn.close()

    config_drift = [r for r in config_results if r[1] == 'config-drift']
    if args.check:
        drift = [r for r in results if r[1] == 'would-change']
        if drift:
            print('\n%d seed file(s) out of sync. Run: ./dev python3 -m servers.tools.sync_prompts'
                  % len(drift), file=sys.stderr)
        if config_drift:
            print('\n%d seed config dict(s) drifted from the active config: %s\n'
                  'Edit the *_INTERACTION_DEFAULT dict in the consumer\'s contract '
                  'file (see the defaults note in servers/interaction_seed.py for '
                  'the name->file map), then bump SEED_PROMPTS_VERSION so existing '
                  'installs receive the fix.'
                  % (len(config_drift), ', '.join(n for n, _ in config_drift)),
                  file=sys.stderr)
        if drift or config_drift:
            return 1
        print('\nAll seed files and configs in sync with DB.')
        return 0
    if config_drift:
        print('\nNOTE: %d seed config dict(s) still drifted (not auto-written): %s'
              % (len(config_drift), ', '.join(n for n, _ in config_drift)),
              file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
