#!/bin/bash
# Shared brain DB resolution — sourced by all hook scripts.
# Boot sets BRAIN_DB_DIR once; other hooks reuse it or re-resolve.
#
# Usage: source "$(dirname "$0")/resolve-brain-db.sh"
# After sourcing: BRAIN_DB_DIR, BRAIN_SERVER_DIR, PLUGIN_ROOT, BRAIN_PYTHON are set.
# If no brain.db found, BRAIN_DB_DIR is empty — caller should exit 0.

# Ensure the isolated runtime is installed and BRAIN_PYTHON / PATH point at it.
# First hook invocation on a fresh install blocks ~15s downloading uv + Python
# + deps. Every subsequent invocation is ~8ms (sentinel fast path).
# ${BASH_SOURCE:-$0}: BASH_SOURCE is unset under POSIX sh — fall back to $0
# instead of silently resolving to cwd (observed: "brain-env.sh doesn't exist").
# NO [0] subscript: bare $BASH_SOURCE is element 0 in bash, while the array
# subscript is a Bad substitution under dash (Linux /bin/sh) that kills the
# fallback entirely.
_RESOLVE_DIR="$(cd "$(dirname "${BASH_SOURCE:-$0}")" && pwd)"
source "$_RESOLVE_DIR/brain-env.sh"

# Always resolve from script location — never use CLAUDE_PLUGIN_ROOT cache.
# The cache can be stale (old code, old socket protocol). Working dir is truth.
PLUGIN_ROOT="$(cd "$_RESOLVE_DIR/../.." && pwd)"
BRAIN_SERVER_DIR="$PLUGIN_ROOT/servers"

# Persist the resolution for non-hook shells. CLAUDE_PLUGIN_DATA and
# CLAUDE_PLUGIN_OPTION_* exist ONLY in hook executions — a skill's Bash shell,
# a user terminal, or launchd sees none of them, so without this file they
# cannot find a brain that lives at the $CLAUDE_PLUGIN_DATA default. Hooks
# persist what they resolve; everyone else reads it (step 4b below).
# Generated file — user config stays untouched in ../brain/env.
# BRAIN_RESOLVE_NO_PERSIST: consumers of the resolution that are not an
# authority on it (brain-daemon — launchd hands it a baked snapshot) set
# this so a relaunch can't clobber a fresher hook-persisted record with
# stale baked state.
_brain_persist_state() {
  [ -z "${BRAIN_RESOLVE_NO_PERSIST:-}" ] || return 0
  [ -n "$BRAIN_DB_DIR" ] && [ -f "$BRAIN_DB_DIR/brain.db" ] || return 0
  local _dir _state _content _existing
  _dir="${XDG_CONFIG_HOME:-$HOME/.config}/brain"
  _state="$_dir/resolved.env"
  # Values are QUOTED — the file is `.`-sourced by consumers (skills,
  # terminals), and an unquoted path with a space breaks sourcing silently.
  _content="# generated by resolve-brain-db.sh — do not edit (user config lives in ./env)
BRAIN_DB_DIR='$BRAIN_DB_DIR'
PLUGIN_ROOT='$PLUGIN_ROOT'"
  # $(<file) is a bash builtin read — no cat fork on this every-hook path.
  _existing=""
  [ -f "$_state" ] && _existing="$(<"$_state")"
  if [ "$_content" != "$_existing" ]; then
    mkdir -p "$_dir" 2>/dev/null
    # tmp + mv: atomic replace — concurrent hooks/skills may be sourcing it.
    printf '%s\n' "$_content" > "$_state.tmp.$$" 2>/dev/null \
      && mv -f "$_state.tmp.$$" "$_state" 2>/dev/null \
      || rm -f "$_state.tmp.$$" 2>/dev/null
  fi
}

# userConfig: a brain path the user set when enabling the plugin. Claude Code
# injects it as CLAUDE_PLUGIN_OPTION_BRAIN_PATH (casing unpinned — check both).
# The "I already have a brain, here's where" install answer. Shell/env
# BRAIN_DB_DIR still wins (fill only when unset), mirroring the api_key rule.
# NOTE: reaches the daemon on the hook/Popen path; a launchd-spawned daemon
# won't see CLAUDE_PLUGIN_OPTION_* (see docs/DISTRIBUTION-READINESS.md §2.1).
if [ -z "${BRAIN_DB_DIR:-}" ]; then
  BRAIN_DB_DIR="${CLAUDE_PLUGIN_OPTION_BRAIN_PATH:-${CLAUDE_PLUGIN_OPTION_brain_path:-}}"
  if [ -n "$BRAIN_DB_DIR" ]; then
    # Honor the chosen location even if it doesn't exist yet — create it so the
    # resolution chain adopts it instead of silently falling through to the
    # default brain. A typo then surfaces as an empty brain at the named path
    # (visible), not a hidden default elsewhere.
    mkdir -p "$BRAIN_DB_DIR" 2>/dev/null
    export BRAIN_DB_DIR
  fi
fi

# If BRAIN_DB_DIR already set and valid (e.g. from boot), skip resolution
if [ -n "$BRAIN_DB_DIR" ] && [ -f "$BRAIN_DB_DIR/brain.db" ]; then
  export BRAIN_DB_DIR BRAIN_SERVER_DIR PLUGIN_ROOT
  _brain_persist_state
  return 0 2>/dev/null || true
fi

# Full resolution chain (runs at boot or if env not set).
#
# Priority is: existing-brain-found > standard-location > Cowork > legacy.
# Auto-create only happens at the standard or Cowork location, never at the
# legacy path (existing users who never migrated must opt in explicitly).
DB_DIR=""

# 1. Explicit override — adopted outright only when a brain actually lives
#    there. A dir WITHOUT brain.db is demoted to a hint of last resort (used
#    below only if no rung finds a real brain): a daemon relaunched off a
#    stale plist-baked path must follow the ladder to the brain that moved
#    (resolved.env, step 4b), not birth a shadow brain at the abandoned dir —
#    while a genuinely fresh install (baked dir exists, daemon creates
#    brain.db on first load) still lands on the hint.
_ENV_HINT=""
if [ -n "$BRAIN_DB_DIR" ] && [ -d "$BRAIN_DB_DIR" ]; then
  if [ -f "$BRAIN_DB_DIR/brain.db" ]; then
    DB_DIR="$BRAIN_DB_DIR"
  else
    _ENV_HINT="$BRAIN_DB_DIR"
  fi
fi

# 2. Cowork: search mounted AgentsContext directories for an existing brain
if [ -z "$DB_DIR" ] && [ -d "/sessions" ]; then
  for candidate in /sessions/*/mnt/AgentsContext/brain; do
    [ -f "$candidate/brain.db" ] 2>/dev/null && DB_DIR="$candidate" && break
  done 2>/dev/null
fi

# 3. Standard Claude Code plugin data location ($CLAUDE_PLUGIN_DATA is set
#    by Claude Code per-plugin and survives plugin updates — the documented
#    convention for plugin-owned runtime state).
if [ -z "$DB_DIR" ] && [ -n "${CLAUDE_PLUGIN_DATA:-}" ] && [ -f "$CLAUDE_PLUGIN_DATA/brain/brain.db" ]; then
  DB_DIR="$CLAUDE_PLUGIN_DATA/brain"
fi

# 4. Legacy local path (~/AgentsContext/brain/) — supported for
#    pre-CLAUDE_PLUGIN_DATA installs. New installs land at $CLAUDE_PLUGIN_DATA.
if [ -z "$DB_DIR" ] && [ -f "$HOME/AgentsContext/brain/brain.db" ]; then
  DB_DIR="$HOME/AgentsContext/brain"
fi

# 4b. Persisted state from a prior hook run (written by _brain_persist_state).
#     The path a non-hook shell (skill Bash, terminal, launchd) lands on when
#     the brain lives at the $CLAUDE_PLUGIN_DATA default it cannot see.
#     Read by sourcing in a subshell — the SAME mechanism every other consumer
#     of this file uses (skills `.`-source it), so one format, one parser.
if [ -z "$DB_DIR" ]; then
  _state_env="${XDG_CONFIG_HOME:-$HOME/.config}/brain/resolved.env"
  if [ -f "$_state_env" ]; then
    _state_db_dir="$(BRAIN_DB_DIR=''; . "$_state_env" 2>/dev/null; printf '%s' "$BRAIN_DB_DIR")"
    [ -n "$_state_db_dir" ] && [ -f "$_state_db_dir/brain.db" ] && DB_DIR="$_state_db_dir"
  fi
fi

# 4c. The demoted explicit hint (step 1): no rung found an existing brain,
#     so the explicitly-named empty dir is where a new one belongs — beats
#     auto-creating at the standard location.
if [ -z "$DB_DIR" ] && [ -n "$_ENV_HINT" ]; then
  DB_DIR="$_ENV_HINT"
fi

# 5. Standard first-run: create at $CLAUDE_PLUGIN_DATA/brain
# ${:-} guards (here and step 3): CLAUDE_PLUGIN_DATA exists only in hook
# executions — this file is also sourced by set -u launchers (brain-dashboard)
# and terminals, where a bare deref kills the shell under nounset.
if [ -z "$DB_DIR" ] && [ -n "${CLAUDE_PLUGIN_DATA:-}" ]; then
  DB_DIR="$CLAUDE_PLUGIN_DATA/brain"
  mkdir -p "$DB_DIR" 2>/dev/null
fi

# 6. Cowork first-run: create in mounted AgentsContext
if [ -z "$DB_DIR" ] && [ -d "/sessions" ]; then
  for ac_dir in /sessions/*/mnt/AgentsContext; do
    if [ -d "$ac_dir" ] 2>/dev/null; then
      DB_DIR="$ac_dir/brain"
      mkdir -p "$DB_DIR" 2>/dev/null
      break
    fi
  done 2>/dev/null
fi

BRAIN_DB_DIR="$DB_DIR"
export BRAIN_DB_DIR BRAIN_SERVER_DIR PLUGIN_ROOT
_brain_persist_state
