"""Pipeline Contract — shared constants and utilities for the recall/encoding pipeline.

This file contains cross-boundary constants used by multiple stages.
Boundary-specific logic lives in dedicated contracts:
- scales/s1/surface_contract.py — S1 Surface (relevance surfacing, formatting, enrichment)
- scales/s1/encode_contract.py — S1 turn encoder (Sonnet config, node formatting, catalog)

Key names are re-exported here for convenience. Boundary-specific code should
import from the specific contract directly.

contract.py defines what fields a node HAS.
pipeline_contract.py defines what fields FLOW at each stage.
"""

from .scales.s1.surface_contract import _relative_time  # noqa: F401 — canonical definition in surface_contract


# ═══════════════════════════════════════════════════════════════
# NODE FIELDS — what to include at each stage
# ═══════════════════════════════════════════════════════════════

# Core fields present in every pipeline stage
NODE_CORE_FIELDS = {
    'id', 'type', 'title', 'content', 'confidence', 'locked',
    'revised_at', 'created_at',
}

# Additional fields for richer contexts
NODE_EXTENDED_FIELDS = NODE_CORE_FIELDS | {
    'access_count', 'encoding_source', 'content_summary',
    'emotion', 'emotion_label', 'updated_at',
}


# ═══════════════════════════════════════════════════════════════
# EMBEDDING GROUPS — multi-vector architecture for recall
# ═══════════════════════════════════════════════════════════════

EMBEDDING_GROUPS = {
    # Group 1: Title — the diagnostic pointer. Always exists. Highest weight.
    'title': {
        'weight': 1.00,
        'fields': ['title'],
        'vector_type': 'title',
        'always_compute': True,
    },
    # Group 2: Blend — title+content embedding. Stored as _primary in node_enrichments.
    'blend': {
        'weight': 0.85,
        'fields': ['title', 'content'],
        'vector_type': '_primary',
        'always_compute': True,
    },
    # Group 3: High-priority metadata — when is this relevant + who said it.
    'high_meta': {
        'weight': 0.70,
        'fields': ['situation', 'user_raw_quote', 'anchor_raw_quote'],
        'vector_type': 'high_meta',
        'always_compute': False,
    },
    # Group 4: Other metadata — why was this stored + behavioral patterns + emergent.
    'other_meta': {
        'weight': 0.40,
        'fields': ['reasoning', 'correction_pattern', 'source_context', '_emergent'],
        'vector_type': 'other_meta',
        'always_compute': False,
    },
    # Group 5: Edge context — what this node's connections say about it.
    # Embeds concatenated edge descriptions (not relation type strings).
    # Weighted by edge family importance. Enables recall to find nodes
    # through their relationship descriptions, not just their own content.
    'edge_context': {
        'weight': 0.55,
        'fields': ['_edge_descriptions'],  # Special: loaded from edge_relations table
        'vector_type': 'edge_context',
        'always_compute': False,
    },
    # Group 6: Question — "What would someone ask to find this?"
    # Generated by S2 Healer (Haiku), stored in node_metadata_kv as 'question'.
    # Bridges vocabulary gap: node uses technical terms, question uses how people ask.
    # Highest-impact findability signal — scored 0.83 where content scored 0.40 in eval.
    'question': {
        'weight': 0.90,
        'fields': ['question'],  # Read from node_metadata_kv
        'vector_type': 'question',
        'always_compute': False,
    },
}

# Scoring method for combining group vectors
EMBEDDING_SCORING_METHOD = 'top2_avg'

# KV fields to skip when building embedding text (not semantic content)
EMBEDDING_SKIP_FIELDS = {
    'metadata_created_at', 'validation_count', 'last_validated',
    'alternatives', 'change_impacts',
}

# Max chars per field when building group embedding text
EMBEDDING_FIELD_CHAR_LIMIT = 300


# ═══════════════════════════════════════════════════════════════
# NODE TYPE EXCLUSIONS — which types are excluded from which operations
# Central registry so exclusions don't scatter across files as hardcoded strings.
# ═══════════════════════════════════════════════════════════════

NODE_TYPE_EXCLUSIONS = {
    # S2 Healer: community nodes managed by S2CE, not the healer
    'healer': {'community'},

    # S2 Consolidation: don't merge community nodes with regular nodes
    'consolidation': {'community'},

    # S2 Community decoder: don't nest communities inside communities
    'community_member_scan': {'community'},

    # Health check: coverage metrics for regular nodes only
    'health_check': {'community'},

    # Recall: NO exclusions — community nodes participate in recall
    'recall': set(),
}


def get_excluded_types(operation: str) -> set:
    """Get node types excluded from a given operation.

    Args:
        operation: Key from NODE_TYPE_EXCLUSIONS (e.g. 'healer', 'recall')

    Returns: set of type strings to exclude, or empty set if no exclusions.
    """
    return NODE_TYPE_EXCLUSIONS.get(operation, set())


def excluded_types_sql(operation: str, column: str = 'n.type') -> str:
    """Generate SQL fragment for type exclusion.

    Returns: "AND n.type NOT IN ('community')" or "" if no exclusions.
    Usage: f"SELECT ... FROM nodes n WHERE n.archived=0 {excluded_types_sql('healer')}"
    """
    excluded = get_excluded_types(operation)
    if not excluded:
        return ''
    quoted = ','.join("'%s'" % t for t in sorted(excluded))
    return " AND %s NOT IN (%s)" % (column, quoted)


def get_group_fields(group_name):
    """Get the field names for an embedding group. Used by remember() and revise()."""
    group = EMBEDDING_GROUPS.get(group_name, {})
    return [f for f in group.get('fields', []) if f != '_emergent']


def get_group_weight(vector_type):
    """Get the z-index weight for a vector type. Used by recall scoring."""
    for group in EMBEDDING_GROUPS.values():
        if group.get('vector_type') == vector_type:
            return group['weight']
    return EMBEDDING_GROUPS['other_meta']['weight']  # default for unknown types


# ═══════════════════════════════════════════════════════════════
# TRUNCATION LIMITS — per stage, per field
# ═══════════════════════════════════════════════════════════════

PIPELINE = {
    'user_message_store': 500,
    'user_message_query': 500,
    'assistant_response_store': 4000,
    'recent_message_content': 300,
    'recall_log_query': 500,
    'recall_log_title': 80,
    'recall_log_snippet': 150,
    'encoding_state_compat': 2000,
}


# ═══════════════════════════════════════════════════════════════
# SURFACE CONFIG — MCP output and pre-edit suggestions
# ═══════════════════════════════════════════════════════════════

# MCP tool output (direct recall by Claude)
MCP_OUTPUT = {
    'content_limit': None,
    'max_results': 20,
    'enrich_top_n': 3,
}

# Pre-edit suggestions
PRE_EDIT = {
    'title_limit': 80,
    'content_limit_engineering': 350,
    'content_limit_code': 350,
    'content_limit_other': 250,
    'content_limit_impact': 300,
}


# ═══════════════════════════════════════════════════════════════
# SHARED FORMATTERS — used across boundaries
# ═══════════════════════════════════════════════════════════════

def format_node_header(node, id_length=8):
    """Standard one-line node header used across all stages."""
    locked = "LOCKED " if node.get("locked") else ""
    return "[%s] %s%s (id:%s, conf:%.2f, revised:%s, created:%s)" % (
        node.get("type", "?"),
        locked,
        node.get("title", "?"),
        str(node.get("id", ""))[:id_length],
        node.get("confidence") or 0,
        node.get("revised_at") or "never",
        str(node.get("created_at") or "")[:10],
    )


def format_neighbor_d1(nb):
    """Standard degree-1 neighbor line."""
    from .scales.s1.surface_contract import NEIGHBOR_TRUNCATION
    t = NEIGHBOR_TRUNCATION
    locked = "LOCKED " if nb.get("locked") else ""
    line = "  → %s: %s\"%s\" (%s, id:%s, conf:%.2f, revised:%s)" % (
        nb.get("relation", "related"),
        locked,
        str(nb.get("title", ""))[:t['d1_title']],
        nb.get("type", "?"),
        str(nb.get("id", ""))[:t['d1_id']],
        nb.get("confidence") or 0,
        nb.get("revised_at") or "never",
    )
    summary = nb.get("content_summary") or ""
    if summary:
        line += "\n      %s" % summary[:t['d1_content_summary']]
    return line


def format_neighbor_d2(nb):
    """Standard degree-2 neighbor breadcrumb."""
    from .scales.s1.surface_contract import NEIGHBOR_TRUNCATION
    t = NEIGHBOR_TRUNCATION
    return "\"%s\" (%s, id:%s)" % (
        str(nb.get("title", ""))[:t['d2_title']],
        nb.get("type", "?"),
        str(nb.get("id", ""))[:t['d2_id']],
    )


# ═══════════════════════════════════════════════════════════════
# NODE REFERENCE — the bare minimum for any node mention
# ═══════════════════════════════════════════════════════════════
#
# Whenever a node appears as a connection, correction, neighbor,
# or any reference — it carries at least these fields.

NODE_REF_FIELDS = ('id', 'type', 'title', 'confidence', 'locked', 'created_at', 'revised_at')

EDGE_REF_FIELDS = ('relation', 'weight', 'description')

# Connections = NODE_REF_FIELDS + EDGE_REF_FIELDS
# Corrections = NODE_REF_FIELDS + direction + content
# Traverse neighbors = NODE_REF_FIELDS + EDGE_REF_FIELDS + content (truncated) + seed_id


# ═══════════════════════════════════════════════════════════════
# TRAVERSE — the enriched cluster atom
# ═══════════════════════════════════════════════════════════════
#
# Given seed node IDs, light them up: follow edges (excluding co_accessed),
# attach correction chains, attach metadata. One function, every consumer.
#
# Callers: boot (S0), MCP recall, S1 Surface, get_node/get_nodes.

TRAVERSE_EXCLUDED_EDGES = {'co_accessed', 'emergent_bridge'}


def traverse(brain, seed_ids, depth=1, limit_per_seed=3):
    """The atom: seed IDs → enriched cluster.

    Returns: {
        'neighbors': [{id, type, title, content, edge_type, edge_weight,
                        edge_description, confidence, seed_id}, ...],
        'corrections': {node_id: [{id, title, direction}, ...]},
        'metadata': {node_id: {key: value, ...}},
    }
    """
    from .dal import NodeDAL
    from .dal_metadata import MetadataDAL
    from .scales.s1.surface_contract import correction_enrich

    conn = brain.conn
    ndal = NodeDAL(conn)
    mdal = MetadataDAL(conn)

    # Resolve short IDs
    resolved_ids = set()
    for sid in seed_ids:
        full = ndal.resolve_id(sid) if len(str(sid)) < 16 else sid
        if full:
            resolved_ids.add(full)

    if not resolved_ids:
        return {'neighbors': [], 'corrections': {}, 'metadata': {}}

    # ── Graph expansion via GraphDAL (v25 — archived + noise centralized) ──
    from .dal import GraphDAL
    graph_dal = GraphDAL(conn)
    seen = set(resolved_ids)
    neighbors = []
    excluded = set(TRAVERSE_EXCLUDED_EDGES)

    for full_id in resolved_ids:
        rows = graph_dal.get_neighbors(
            full_id,
            limit=limit_per_seed,
            exclude_relations=excluded,
            exclude_node_ids=seen,
            content_preview_chars=300,
        )
        for r in rows:
            if r['id'] not in seen:
                seen.add(r['id'])
                neighbors.append({
                    "id": r['id'], "type": r['type'], "title": r['title'],
                    "content": r.get('content_preview', ''),
                    "edge_type": r['relation'],
                    "edge_weight": r['weight'],
                    "edge_description": r.get('edge_description') or '',
                    "confidence": r['confidence'],
                    "locked": r['locked'] == 1,
                    "created_at": r['created_at'], "revised_at": r['revised_at'],
                    "direction": r['direction'],
                    "seed_id": full_id,
                })

    # ── Correction chains (seeds + neighbors) ──
    all_ids = set()
    for sid in resolved_ids:
        all_ids.add(sid)
        all_ids.add(sid[:8])
    for nb in neighbors:
        all_ids.add(nb['id'])
        all_ids.add(nb['id'][:8])

    corrections = correction_enrich(all_ids, conn)

    # ── Metadata for seeds ──
    metadata = {}
    for sid in resolved_ids:
        meta = mdal.get(sid)
        if meta:
            metadata[sid] = meta
            metadata[sid[:8]] = meta

    return {
        'neighbors': neighbors,
        'corrections': corrections,
        'metadata': metadata,
    }



# ═══════════════════════════════════════════════════════════════
# RE-EXPORTS — many callers import from pipeline_contract.
# Migrate to specific contracts when touching these callers.
# ═══════════════════════════════════════════════════════════════

from .scales.s1.surface_contract import (  # noqa: E402, F401
    SURFACE,
    CANDIDATES_FILE,
    NEIGHBOR_D1_FIELDS,
    NEIGHBOR_D2_FIELDS,
    NEIGHBOR_D3_FIELDS,
    NEIGHBOR_TRUNCATION,
    PRECISION,
    format_candidate_for_surface,
    build_surface_prompt,
    format_surface_output,
    enrich_candidate_metadata,
    correction_enrich,
)
JUDGE = SURFACE  # legacy alias
format_candidate_for_judge = format_candidate_for_surface
build_judge_prompt = build_surface_prompt
format_judge_output = format_surface_output

from .scales.s1.encode_contract import (  # noqa: E402, F401
    ENCODING_AGENT,
    build_encoder_node_catalog,
)
