"""Pipeline Contract — shared constants and utilities for the recall/encoding pipeline.

This file contains cross-boundary constants used by multiple stages.
Boundary-specific logic lives in dedicated contracts:
- scales/s1/surface_contract.py — S1 Surface (relevance surfacing, formatting, enrichment)
- scales/s1/encode_contract.py — S1 turn encoder (Sonnet config, node formatting, catalog)

Key names are re-exported here for convenience. Boundary-specific code should
import from the specific contract directly.

contract.py defines what fields a node HAS.
pipeline_contract.py defines what fields FLOW at each stage.
"""

from .scales.s1.surface_contract import _relative_time  # noqa: F401 — canonical definition in surface_contract


# ═══════════════════════════════════════════════════════════════
# NODE FIELDS — what to include at each stage
# ═══════════════════════════════════════════════════════════════

# Core fields present in every pipeline stage
NODE_CORE_FIELDS = {
    'id', 'type', 'title', 'content', 'confidence', 'locked',
    'revised_at', 'created_at',
}

# Additional fields for richer contexts
NODE_EXTENDED_FIELDS = NODE_CORE_FIELDS | {
    'access_count', 'encoding_source', 'content_summary',
    'emotion', 'emotion_label', 'updated_at',
}


# ═══════════════════════════════════════════════════════════════
# EMBEDDING GROUPS — multi-vector architecture
#
# Two cohorts coexist:
#
#   LEGACY (blended) — used by brain.recall() for candidate ranking.
#     `title`, `_primary` (title+content), `high_meta` (situation+quotes),
#     `other_meta` (reasoning+patterns), `edge_context`, `question`.
#     Non-zero `weight`, participate in top2_avg scoring.
#
#   FIELD (per-field, unblended) — used by S1 Surface's activation kernel.
#     One vector per semantic field. Weight = 0 so they don't ripple into
#     recall() scoring; the kernel reads them directly.
#
# Why both: legacy vectors capture whole-node semantics well for retrieval
# ranking. Field vectors capture per-field signal so activation can fade per
# field (query about "what did they say" → their_raw_quote field lights up;
# query about "when does this apply" → situation field lights up). Blending
# them together in legacy `high_meta` made each query score muddled.
#
# Migration: new nodes get both cohorts at encode time. Old nodes get lazy
# backfill when the activation kernel encounters missing field vectors.
# The kernel has a fallback chain (field → blend) so old nodes still work
# with reduced granularity until backfill.
# ═══════════════════════════════════════════════════════════════

EMBEDDING_GROUPS = {
    # ── LEGACY COHORT (used by recall() for candidate ranking) ─────────

    # The diagnostic pointer. Always exists. Highest weight.
    'title': {
        'weight': 1.00,
        'fields': ['title'],
        'vector_type': 'title',
        'always_compute': True,
        'cohort': 'legacy',
    },
    # Title+content blend. Stored as `_primary` in node_enrichments.
    'blend': {
        'weight': 0.85,
        'fields': ['title', 'content'],
        'vector_type': '_primary',
        'always_compute': True,
        'cohort': 'legacy',
    },
    # When is this relevant + who said it (situation + quotes blend).
    'high_meta': {
        'weight': 0.70,
        'fields': ['situation', 'their_raw_quote', 'my_raw_quote'],
        'vector_type': 'high_meta',
        'always_compute': False,
        'cohort': 'legacy',
    },
    # Why was this stored + behavioral patterns + emergent (reasoning blend).
    'other_meta': {
        'weight': 0.40,
        'fields': ['reasoning', 'correction_pattern', 'source_context', '_emergent'],
        'vector_type': 'other_meta',
        'always_compute': False,
        'cohort': 'legacy',
    },
    # Edge context — concatenated edge descriptions. Enables recall to find
    # nodes through their relationship descriptions, not just their own content.
    'edge_context': {
        'weight': 0.55,
        'fields': ['_edge_descriptions'],
        'vector_type': 'edge_context',
        'always_compute': False,
        'cohort': 'legacy',
    },
    # "What would someone ask to find this?" — Haiku-generated by S2 Healer,
    # stored in node_metadata_kv as 'question'. Bridges vocabulary gap.
    'question': {
        'weight': 0.90,
        'fields': ['question'],
        'vector_type': 'question',
        'always_compute': False,
        'cohort': 'legacy',
    },

    # ── FIELD COHORT (used by S1 Surface activation kernel) ────────────
    # Weight=0 so these don't participate in recall() top2_avg scoring —
    # they exist solely to give the activation kernel per-field resolution.

    # Content body alone — split from `_primary` blend.
    'field_content': {
        'weight': 0.0,
        'fields': ['content'],
        'vector_type': 'content',
        'always_compute': False,
        'cohort': 'field',
    },
    # situation has NO field-cohort vector: it's served by the legacy dedicated
    # `_situation` vector (full-text, shared with recall's situation-boost) via
    # FIELD_VECTOR_FALLBACK['situation']. One situation vector, two consumers.
    # Reasoning alone — split from `other_meta`.
    'field_reasoning': {
        'weight': 0.0,
        'fields': ['reasoning'],
        'vector_type': 'reasoning',
        'always_compute': False,
        'cohort': 'field',
    },
    # Their verbatim voice — split from `high_meta`.
    'field_their_raw_quote': {
        'weight': 0.0,
        'fields': ['their_raw_quote'],
        'vector_type': 'their_raw_quote',
        'always_compute': False,
        'cohort': 'field',
    },
    # My own verbatim voice — split from `high_meta`. Distinct channel from
    # their quote; a query about my reasoning should find this cleanly
    # without interference from their words.
    'field_my_raw_quote': {
        'weight': 0.0,
        'fields': ['my_raw_quote'],
        'vector_type': 'my_raw_quote',
        'always_compute': False,
        'cohort': 'field',
    },
}


# Fallback chain for the activation kernel: when a field vector is missing
# on an old node (not yet backfilled), fall back to the legacy blend that
# contains the field's content. Ordered best-match-first.
FIELD_VECTOR_FALLBACK = {
    'title':              ['title'],  # no fallback needed — always computed
    'content':            ['_primary'],
    'situation':          ['_situation', 'high_meta'],
    'reasoning':          ['other_meta'],
    'their_raw_quote':    ['high_meta'],
    'my_raw_quote':       ['high_meta'],
    'question':           ['question'],  # no blend, direct
}


def field_vector_types():
    """Return the list of per-field vector_types the activation kernel reads.

    Stable order: title → content → situation → reasoning → their quote
    → my quote → question. Determinism matters for test assertions and
    trace readability.
    """
    return ['title', 'content', 'situation', 'reasoning',
            'their_raw_quote', 'my_raw_quote', 'question']


def vectors_affected_by(field_name: str) -> set:
    """Given a field name, return vector_types whose embedding text depends
    on it — these go stale when the field is updated and must be deleted
    so embed_queue's backfill creates fresh ones.

    Derived from EMBEDDING_GROUPS — single source of truth. Special case:
    `_situation` derives from node_metadata_kv['situation'] but is NOT an
    EMBEDDING_GROUPS entry (it's the legacy dedicated situation vector, written
    by its own backfill scan), so it's added explicitly. Updating `situation`
    also invalidates `high_meta` (which blends situation + quotes); there is no
    longer a `field_situation`/`situation` vector to invalidate.

    Used by `brain.revise()` to invalidate stale vectors. Without this,
    `VectorDAL.find_missing()` skips rows that exist (text in kv changed
    but the row carries old embedding), and the vector permanently
    encodes outdated text.
    """
    affected = set()
    for spec in EMBEDDING_GROUPS.values():
        if field_name in spec.get('fields', []):
            affected.add(spec['vector_type'])
    # `_situation` is the dedicated situation vector — derived from
    # kv['situation'] by its own backfill scan, NOT an EMBEDDING_GROUPS entry,
    # so the loop above never picks it up. There is no `field_situation` cohort:
    # situation is served by `_situation` via FIELD_VECTOR_FALLBACK (one vector,
    # two consumers — see EMBEDDING_GROUPS). So `_situation` + `high_meta` are
    # the only situation-dependent vectors. Add `_situation` explicitly.
    if field_name == 'situation':
        affected.add('_situation')
    return affected

# Scoring method for combining group vectors
EMBEDDING_SCORING_METHOD = 'top2_avg'

# KV fields to skip when building embedding text (not semantic content)
EMBEDDING_SKIP_FIELDS = {
    'metadata_created_at', 'validation_count', 'last_validated',
    'alternatives', 'change_impacts',
}

# Max chars per field when building group embedding text
EMBEDDING_FIELD_CHAR_LIMIT = 300

# Dead-handler detection floor. If backfill_vectors finds at least this many
# ELIGIBLE candidates for a group (find_missing now filters to nodes that
# should yield text) but stores ZERO embeddings, the group's handler built no
# text — a dead/missing handler or a total embed failure. This is the exact
# silent-partial that hid edge_context's 0-row bug (a configured 0.55-weighted
# group that never produced a row). The floor avoids false trips on a 1-2 node
# tail; rely on _log_error's rate-limiter for repeat suppression.
EMBEDDING_DEAD_HANDLER_MIN_CANDIDATES = 5


# ═══════════════════════════════════════════════════════════════
# NODE TYPE EXCLUSIONS — which types are excluded from which operations
# Central registry so exclusions don't scatter across files as hardcoded strings.
# ═══════════════════════════════════════════════════════════════

NODE_TYPE_EXCLUSIONS = {
    # S2 Healer: community nodes managed by S2CE, not the healer
    'healer': {'community'},

    # S2 Consolidation: don't merge community nodes with regular nodes
    'consolidation': {'community'},

    # S2 Community decoder: don't nest communities inside communities
    'community_member_scan': {'community'},

    # Health check: coverage metrics for regular nodes only
    'health_check': {'community'},

    # Recall: community nodes are S2 navigation/consolidation structure,
    # not surfaceable memories — excluded from the recall
    # pool. Explicit dict filters on type bypass this (deliberate community
    # queries — dashboard, S2, direct asks — still work).
    'recall': {'community'},
}


def get_excluded_types(operation: str) -> set:
    """Get node types excluded from a given operation.

    Args:
        operation: Key from NODE_TYPE_EXCLUSIONS (e.g. 'healer', 'recall')

    Returns: set of type strings to exclude, or empty set if no exclusions.
    """
    return NODE_TYPE_EXCLUSIONS.get(operation, set())


def excluded_types_sql(operation: str, column: str = 'n.type') -> str:
    """Generate SQL fragment for type exclusion.

    Returns: "AND n.type NOT IN ('community')" or "" if no exclusions.
    Usage: f"SELECT ... FROM nodes n WHERE n.archived=0 {excluded_types_sql('healer')}"
    """
    excluded = get_excluded_types(operation)
    if not excluded:
        return ''
    quoted = ','.join("'%s'" % t for t in sorted(excluded))
    return " AND %s NOT IN (%s)" % (column, quoted)


def get_group_weight(vector_type):
    """Get the z-index weight for a vector type. Used by recall scoring."""
    for group in EMBEDDING_GROUPS.values():
        if group.get('vector_type') == vector_type:
            return group['weight']
    return EMBEDDING_GROUPS['other_meta']['weight']  # default for unknown types


# ═══════════════════════════════════════════════════════════════
# TRUNCATION LIMITS — per stage, per field
# ═══════════════════════════════════════════════════════════════

PIPELINE = {
    'user_message_query': 500,
    'assistant_response_store': 4000,
    'recent_message_content': 400,  # upstream cap on the daemon_hooks trace pull;
                                    # must cover SURFACE's per-role display limits —
                                    # enforced by test_pipeline_contract.TestTruncationInvariants.
    'recall_log_query': 500,
    'recall_log_title': 80,
    'recall_log_snippet': 150,
}


# ═══════════════════════════════════════════════════════════════
# SURFACE CONFIG — MCP output and pre-edit suggestions
# ═══════════════════════════════════════════════════════════════

# MCP tool output (direct recall by Claude)
MCP_OUTPUT = {
    'content_limit': None,
    'max_results': 20,
    'enrich_top_n': 3,
}

# Pre-edit suggestions
PRE_EDIT = {
    'title_limit': 80,
    'content_limit_engineering': 350,
    'content_limit_code': 350,
    'content_limit_other': 250,
    'content_limit_impact': 300,
}


# ═══════════════════════════════════════════════════════════════
# SHARED FORMATTERS — used across boundaries
# ═══════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════
# NODE REFERENCE — the bare minimum for any node mention
# ═══════════════════════════════════════════════════════════════
#
# Whenever a node appears as a connection, correction, neighbor,
# or any reference — it carries at least these fields.

NODE_REF_FIELDS = ('id', 'type', 'title', 'confidence', 'locked', 'created_at', 'revised_at')

EDGE_REF_FIELDS = ('relation', 'weight', 'description')

# Connections = NODE_REF_FIELDS + EDGE_REF_FIELDS
# Corrections = NODE_REF_FIELDS + direction + content
# Traverse neighbors = NODE_REF_FIELDS + EDGE_REF_FIELDS + content (truncated) + seed_id


# ═══════════════════════════════════════════════════════════════
# TRAVERSE — the enriched cluster atom
# ═══════════════════════════════════════════════════════════════
#
# Given seed node IDs, light them up: follow edges (noise excluded),
# attach correction chains, attach metadata. One function, every consumer.
#
# Callers: boot (S0), MCP recall, S1 Surface, get_node/get_nodes.

# Traversal exclusions derive from the noise aspect at load time —
# brain.aspects.structural_exclusions (see AspectRegistry._adopt). The old
# TRAVERSE_EXCLUDED_EDGES literal was a dated snapshot of "what noise meant".


def traverse(brain, seed_ids, depth=1, limit_per_seed=3):
    """The atom: seed IDs → enriched cluster.

    Returns: {
        'neighbors': [{id, type, title, content, edge_type, edge_weight,
                        edge_description, confidence, seed_id}, ...],
        'corrections': {node_id: [{id, title, direction}, ...]},
        'metadata': {node_id: {key: value, ...}},
    }
    """
    mdal = brain._meta_kv

    resolved_ids = {sid for sid in seed_ids if sid}

    if not resolved_ids:
        return {'neighbors': [], 'corrections': {}, 'metadata': {}}

    # ── Graph expansion via GraphDAL (v25 — archived + noise centralized) ──
    graph_dal = brain._graph
    seen = set(resolved_ids)
    neighbors = []
    excluded = set(brain.aspects.traversal_exclusions)

    for full_id in resolved_ids:
        rows = graph_dal.get_neighbors(
            full_id,
            limit=limit_per_seed,
            exclude_relations=excluded,
            exclude_node_ids=seen,
            content_preview_chars=300,
        )
        for r in rows:
            if r['id'] not in seen:
                seen.add(r['id'])
                neighbors.append({
                    "id": r['id'], "type": r['type'], "title": r['title'],
                    "content": r.get('content_preview', ''),
                    "edge_type": r['relation'],
                    "edge_weight": r['weight'],
                    "edge_description": r.get('edge_description') or '',
                    "confidence": r['confidence'],
                    "locked": r['locked'] == 1,
                    "created_at": r['created_at'], "revised_at": r['revised_at'],
                    "direction": r['direction'],
                    "seed_id": full_id,
                })

    # ── Correction chains (seeds + neighbors) — aspect-edge walk
    all_ids = set(resolved_ids)
    for nb in neighbors:
        all_ids.add(nb['id'])

    corrections = brain.correction_enrich(all_ids)

    # ── Metadata for seeds ──
    metadata = {}
    for sid in resolved_ids:
        meta = mdal.get(sid)
        if meta:
            metadata[sid] = meta
            metadata[sid[:8]] = meta

    return {
        'neighbors': neighbors,
        'corrections': corrections,
        'metadata': metadata,
    }


# ═══════════════════════════════════════════════════════════════
# RE-EXPORTS — many callers import from pipeline_contract.
# Migrate to specific contracts when touching these callers.
# ═══════════════════════════════════════════════════════════════

from .scales.s1.surface_contract import (  # noqa: E402, F401
    SURFACE,
    CANDIDATE_POOL,
    NEIGHBOR_TRUNCATION,
    format_candidate_for_surface,
    build_surface_prompt,
    enrich_candidate_metadata,
)

from .scales.s1.encode_contract import (  # noqa: E402, F401
    ENCODING_AGENT,
)
