"""Seed for interaction `recall_query_expansion` — DB is authoritative at runtime.

This file ONLY bootstraps fresh brains that have no entry for
recall_query_expansion yet. The runtime path (brain.get_interaction_prompt in
brain_recall._expand_query_via_llm) always reads the DB.
Do NOT edit this file to change prompt behavior — use register_interaction
+ set_interaction_active, then run `./dev python3 -m servers.tools.sync_prompts`
to mirror the ACTIVE version into this file.

Sync mirrors the production-ACTIVE version, not the highest registered.
Dormant candidates (registered but not yet activated — e.g. during a
3-way eval gate) are deliberately excluded from the seed so fresh brains
cannot bypass the eval gate by booting with an untested candidate.

Last sync: DB v1 (2026-08-17T13:52:24, by anchor).
"""

SYSTEM_PROMPT = """Generate 2-3 alternate query phrasings that bridge LEXICAL GAPS — vocabulary differences between how the user asks and how the memory was originally stored. Don't paraphrase. Don't say the same thing in different words.

Each alternate MUST drop or replace at least one specific term from the original query, choosing one of these strategies:

1. STRIP the specific entity, keep the activity:
   "What did I bake for my uncle's birthday party?" → "what I baked for a birthday party"
   "Where did I attend study abroad?" → "country I studied in", "university I went to"

2. REPLACE the specific entity with a category or sibling entity (in case the memory is about a related entity):
   "uncle's birthday" → "family member's birthday", "niece's birthday"
   "feed" → "feed for chickens", "scratch grains for chickens"
   "Memrise" → "language learning apps with mnemonics", "apps for memorization"

3. BROADEN to the category the original is in:
   "siblings count" → "brothers and sisters family"
   "gym time" → "evening workout schedule"

The original query gets searched separately. Your alternates must reach memories the original would NOT.

Return ONLY a JSON array of 2-3 strings, no prose, no explanation.

Query: "{query}"
"""
