"""Encoder prompt examples for s1e §7.6 (v19+).

Examples are structured data — authored once, rendered into prompts at
encoding time. Each example file exports an `EXAMPLE` dict per the schema
implied by `servers/scales/s1/quality_contract.py`.

Architecture:
- Authored format (this directory): rich Python dicts with primary_dims,
  contract_eval, counterfactual_bad, voice_annotations, choice_points.
  Consumed by: future S3 selector, evaluator agent, future Anchor with
  better reasoning.
- Rendered format (generated): compressed prose embedded in the s1e prompt.
  Consumed by: Sonnet at encoding time. Generated by
  `render_for_encoder_prompt()` (not yet built — v20+ work).

Loading all examples:
    from servers.scales.s1.examples import ALL_EXAMPLES

Loading by wave:
    from servers.scales.s1.examples import WAVE_1

Schema for each EXAMPLE dict (illustrative, not enforced — v1):
    id, intent, primary_dims, wave, placement?, source_conversation,
    encoder_cognition, encoder_output, counterfactual_bad?,
    voice_annotations?, contract_eval?, what_this_teaches
"""

from .a1_control_by_request import EXAMPLE as A1
from .a2_action_not_information import EXAMPLE as A2
from .a3_anchor_sees_tom import EXAMPLE as A3
from .a4_brain_is_mirror import EXAMPLE as A4
from .a6_smoothing_severs_binding import EXAMPLE as A6
from .a7_anchor_persists import EXAMPLE as A7
from .b1_methodology_principle_split import EXAMPLE as B1

ALL_EXAMPLES = {
    A6['id']: A6,
    A7['id']: A7,
    A4['id']: A4,
    A1['id']: A1,
    A2['id']: A2,
    A3['id']: A3,
    B1['id']: B1,
}

# §7.6 placement order (v20.1 — adds B1 to fix D31 regression):
#   A6 + A7 + A4 — Anchor self-reference triad (earned habit, declared
#                  identity, structural limit). Frames the entire set.
#   A2 — correction-with-affect (hot register)
#   A3 — trust formation via accurate seeing (partnership register)
#   B1 — methodology + principle split (operator process + Anchor axiom)
#
# A1 dropped from wave_1 (duplicate of fixed canonical Example 4 — "Ask
# the daemon"). Lives in ALL_EXAMPLES for future S3 dynamic selection.
WAVE_1 = [A6, A7, A4, A2, A3, B1]

# Wave 1 — partnership/identity depth (load-bearing)
# Wave 2 — shape diversity (pure reference, quote-as-title, correction lineage,
#          multi-aspect, open-thread with lifecycle)
# Wave 3 — domain breadth (math, poetry, psychology, research) via parallel
#          agent dispatch — proves contract generality or surfaces missed dims
