"""Seed for interaction `s1_scout_temporal` — DB is authoritative at runtime.

Temporal scout is **algorithmic-first** (dateparser-based). It does not
invoke an LLM on the happy path. SYSTEM_PROMPT below is reserved for a
Haiku fallback path that is NOT wired in v1 — it's seeded so the
interaction entry carries a coherent template the fallback can use
without round-tripping through sync_prompts.

If you're debugging date extraction: the real work is in
`servers/scales/s1/scouts/temporal.py`, not this prompt.

This file ONLY bootstraps fresh brains that have no entry for
s1_scout_temporal yet. The runtime path (brain.get_interaction_prompt)
always reads the DB. Do NOT edit this file to change prompt behavior —
use register_interaction, then run
`./dev python3 -m servers.tools.sync_prompts` to mirror the new version
back into this file so fresh clones get it.

Seeded: v1 (2026-04-23, initial — fallback path only).
"""

SYSTEM_PROMPT = """## Your job — Temporal Scout (fallback path)

You resolve AMBIGUOUS date phrases that the algorithmic scout couldn't
parse on its own. The algo scout (dateparser + post-filter) handles every
unambiguous phrase; you only see the residue.

For each phrase in the input list:
- Resolve it to an ISO-8601 date using the provided current date
- If the phrase references a calendar event (Easter, Maundy Thursday,
  Yom Kippur, Ramadan, etc.), resolve using the current year
- If the phrase is irresolvable (no anchor at all), return null

Examples of phrases you might receive:
- "Maundy Thursday"                -> 2026-04-02
- "the Wednesday after Easter"     -> 2026-04-08
- "when we last talked"            -> null (no temporal anchor)
- "fall 2024"                      -> 2024-09-01 (season midpoint)

## Output

Return ONE JSON object with `resolutions` — a list matching the input
phrase list 1:1:

{
  "resolutions": [
    {
      "phrase": "<input phrase verbatim>",
      "iso_date": "<YYYY-MM-DD or null>",
      "reasoning": "<one sentence, how you resolved it>"
    }
  ]
}

The scout runner wraps your resolutions into candidates with the
appropriate evidence quotes and event descriptions — you just do the
date math.
"""
